version: '2'
services:
  zookeeper:
    image: aliciahan/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      testing_net:
        ipv4_address: 10.77.0.2
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.77.0.3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./k1-data:/kafka
    networks:
      testing_net:
        ipv4_address: 10.77.0.3
  kafka2:
    build: .
    expose:
      - "9092"
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.77.0.4
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./k2-data:/kafka
    networks:
      testing_net:
        ipv4_address: 10.77.0.4
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 10.77.0.0/16
